//-------------------------请加下面QQ请求远程辅助运行代码  ID:1811--------------------------
//-----------------更多毕设, 联系QQ1305637939-------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加下面QQ请求远程辅助运行代码----------------------------
package com.model;

/**
 * TKecheng generated by MyEclipse Persistence Tools
 */

public class TKecheng implements java.io.Serializable
{

	// Fields

	private Integer kechengId;

	private String kechengName;

	private String kechengMiaoshu;
	
	private String del;

	// Constructors

	/** default constructor */
	public TKecheng()
	{
	}

	/** full constructor */
	public TKecheng(String kechengName, String kechengMiaoshu)
	{
		this.kechengName = kechengName;
		this.kechengMiaoshu = kechengMiaoshu;
	}

	// Property accessors

	public Integer getKechengId()
	{
		return this.kechengId;
	}

	public void setKechengId(Integer kechengId)
	{
		this.kechengId = kechengId;
	}

	public String getKechengName()
	{
		return this.kechengName;
	}

	public void setKechengName(String kechengName)
	{
		this.kechengName = kechengName;
	}

	public String getKechengMiaoshu()
	{
		return this.kechengMiaoshu;
	}

	public void setKechengMiaoshu(String kechengMiaoshu)
	{
		this.kechengMiaoshu = kechengMiaoshu;
	}

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}//-------------------------请加下面QQ请求远程辅助运行代码  ID:1811--------------------------
//-----------------更多毕设, 联系QQ1305637939-------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加下面QQ请求远程辅助运行代码----------------------------
