//-------------------------请加下面QQ请求远程辅助运行代码  ID:1811--------------------------
//-----------------更多毕设, 联系QQ1305637939-------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加下面QQ请求远程辅助运行代码----------------------------
package com.model;

/**
 * TPeixunchengji generated by MyEclipse Persistence Tools
 */

public class TPeixunchengji implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer peixunId;

	private Integer yuangongId;

	private Integer chengji;
	
	private String yuangongName;

	// Constructors

	/** default constructor */
	public TPeixunchengji()
	{
	}

	/** full constructor */
	public TPeixunchengji(Integer peixunId, Integer yuangongId, Integer chengji)
	{
		this.peixunId = peixunId;
		this.yuangongId = yuangongId;
		this.chengji = chengji;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public String getYuangongName()
	{
		return yuangongName;
	}

	public void setYuangongName(String yuangongName)
	{
		this.yuangongName = yuangongName;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getPeixunId()
	{
		return this.peixunId;
	}

	public void setPeixunId(Integer peixunId)
	{
		this.peixunId = peixunId;
	}

	public Integer getYuangongId()
	{
		return this.yuangongId;
	}

	public void setYuangongId(Integer yuangongId)
	{
		this.yuangongId = yuangongId;
	}

	public Integer getChengji()
	{
		return this.chengji;
	}

	public void setChengji(Integer chengji)
	{
		this.chengji = chengji;
	}

}//-------------------------请加下面QQ请求远程辅助运行代码  ID:1811--------------------------
//-----------------更多毕设, 联系QQ1305637939-------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加下面QQ请求远程辅助运行代码----------------------------
