//-------------------------请加下面QQ请求远程辅助运行代码  ID:1811--------------------------
//-----------------更多毕设, 联系QQ1305637939-------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加下面QQ请求远程辅助运行代码----------------------------
package com.model;

/**
 * TPeixun generated by MyEclipse Persistence Tools
 */

public class TPeixun implements java.io.Serializable
{

	// Fields

	private Integer peixunId;

	private String peixunShijian;

	private String peixunDidian;

	private String peixunNeirong;

	private Integer kechengId;

	private String del;
	
	private String peixunLaoshi;
	
	private String kechengName;

	// Constructors

	/** default constructor */
	public TPeixun()
	{
	}

	/** full constructor */
	public TPeixun(String peixunShijian, String peixunDidian,
			String peixunNeirong, String kechengId, String del)
	{
		this.peixunShijian = peixunShijian;
		this.peixunDidian = peixunDidian;
		this.peixunNeirong = peixunNeirong;
		this.del = del;
	}

	// Property accessors

	public Integer getPeixunId()
	{
		return this.peixunId;
	}

	public void setPeixunId(Integer peixunId)
	{
		this.peixunId = peixunId;
	}

	public String getPeixunShijian()
	{
		return this.peixunShijian;
	}

	public void setPeixunShijian(String peixunShijian)
	{
		this.peixunShijian = peixunShijian;
	}

	public String getPeixunDidian()
	{
		return this.peixunDidian;
	}

	public void setPeixunDidian(String peixunDidian)
	{
		this.peixunDidian = peixunDidian;
	}

	public String getPeixunNeirong()
	{
		return this.peixunNeirong;
	}
	

	public void setPeixunNeirong(String peixunNeirong)
	{
		this.peixunNeirong = peixunNeirong;
	}


	public Integer getKechengId()
	{
		return kechengId;
	}

	public void setKechengId(Integer kechengId)
	{
		this.kechengId = kechengId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public String getKechengName()
	{
		return kechengName;
	}

	public void setKechengName(String kechengName)
	{
		this.kechengName = kechengName;
	}

	public String getPeixunLaoshi()
	{
		return peixunLaoshi;
	}

	public void setPeixunLaoshi(String peixunLaoshi)
	{
		this.peixunLaoshi = peixunLaoshi;
	}

}//-------------------------请加下面QQ请求远程辅助运行代码  ID:1811--------------------------
//-----------------更多毕设, 联系QQ1305637939-------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加下面QQ请求远程辅助运行代码----------------------------
