//-------------------------请加下面QQ请求远程辅助运行代码  ID:1811--------------------------
//-----------------更多毕设, 联系QQ1305637939-------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加下面QQ请求远程辅助运行代码----------------------------
package com.model;

import java.util.Date;

/**
 * TYuangong generated by MyEclipse Persistence Tools
 */

public class TYuangong implements java.io.Serializable
{

	// Fields

	private Integer yuangongId;

	private String yuangongName;

	private String yuangongSex;

	private int yuangongAge;

	private String yuangongXueli;

	private String yuangongZhiwei;

	private String yuangongAddress;

	private String yuangongTel;

	private String yuangongEmail;

	private String yuangongQq;
	
	private int yuangongOrgId;
	
	private String yuangongOrgName;

	private String yuangongOne1;//��־λ��yuangong��

	private String yuangongOne2;//��¼�ʺ�

	private String yuangongOne3;//��¼����

	private String yuangongOne4;

	private Date yuangongOne5;

	private Date yuangongOne6;

	private Integer yuangongOne7;

	private Integer yuangongOne8;

	// Constructors

	/** default constructor */
	public TYuangong()
	{
	}

	/** full constructor */
	public TYuangong(String yuangongName, String yuangongSex,
			 String yuangongXueli, String yuangongZhiwei,
			String yuangongAddress, String yuangongTel, String yuangongEmail,
			String yuangongQq, String yuangongOne1, String yuangongOne2,
			String yuangongOne3, String yuangongOne4, Date yuangongOne5,
			Date yuangongOne6, Integer yuangongOne7, Integer yuangongOne8)
	{
		this.yuangongName = yuangongName;
		this.yuangongSex = yuangongSex;
		this.yuangongXueli = yuangongXueli;
		this.yuangongZhiwei = yuangongZhiwei;
		this.yuangongAddress = yuangongAddress;
		this.yuangongTel = yuangongTel;
		this.yuangongEmail = yuangongEmail;
		this.yuangongQq = yuangongQq;
		this.yuangongOne1 = yuangongOne1;
		this.yuangongOne2 = yuangongOne2;
		this.yuangongOne3 = yuangongOne3;
		this.yuangongOne4 = yuangongOne4;
		this.yuangongOne5 = yuangongOne5;
		this.yuangongOne6 = yuangongOne6;
		this.yuangongOne7 = yuangongOne7;
		this.yuangongOne8 = yuangongOne8;
	}

	// Property accessors

	public Integer getYuangongId()
	{
		return this.yuangongId;
	}

	public void setYuangongId(Integer yuangongId)
	{
		this.yuangongId = yuangongId;
	}

	public String getYuangongName()
	{
		return this.yuangongName;
	}

	public void setYuangongName(String yuangongName)
	{
		this.yuangongName = yuangongName;
	}

	public String getYuangongSex()
	{
		return this.yuangongSex;
	}

	public void setYuangongSex(String yuangongSex)
	{
		this.yuangongSex = yuangongSex;
	}

	public int getYuangongOrgId()
	{
		return yuangongOrgId;
	}

	public void setYuangongOrgId(int yuangongOrgId)
	{
		this.yuangongOrgId = yuangongOrgId;
	}


	public String getYuangongOrgName()
	{
		return yuangongOrgName;
	}

	public void setYuangongOrgName(String yuangongOrgName)
	{
		this.yuangongOrgName = yuangongOrgName;
	}


	public int getYuangongAge()
	{
		return yuangongAge;
	}

	public void setYuangongAge(int yuangongAge)
	{
		this.yuangongAge = yuangongAge;
	}

	public String getYuangongXueli()
	{
		return this.yuangongXueli;
	}

	public void setYuangongXueli(String yuangongXueli)
	{
		this.yuangongXueli = yuangongXueli;
	}

	public String getYuangongZhiwei()
	{
		return this.yuangongZhiwei;
	}

	public void setYuangongZhiwei(String yuangongZhiwei)
	{
		this.yuangongZhiwei = yuangongZhiwei;
	}

	public String getYuangongAddress()
	{
		return this.yuangongAddress;
	}

	public void setYuangongAddress(String yuangongAddress)
	{
		this.yuangongAddress = yuangongAddress;
	}

	public String getYuangongTel()
	{
		return this.yuangongTel;
	}

	public void setYuangongTel(String yuangongTel)
	{
		this.yuangongTel = yuangongTel;
	}

	public String getYuangongEmail()
	{
		return this.yuangongEmail;
	}

	public void setYuangongEmail(String yuangongEmail)
	{
		this.yuangongEmail = yuangongEmail;
	}

	public String getYuangongQq()
	{
		return this.yuangongQq;
	}

	public void setYuangongQq(String yuangongQq)
	{
		this.yuangongQq = yuangongQq;
	}

	public String getYuangongOne1()
	{
		return this.yuangongOne1;
	}

	public void setYuangongOne1(String yuangongOne1)
	{
		this.yuangongOne1 = yuangongOne1;
	}

	public String getYuangongOne2()
	{
		return this.yuangongOne2;
	}

	public void setYuangongOne2(String yuangongOne2)
	{
		this.yuangongOne2 = yuangongOne2;
	}

	public String getYuangongOne3()
	{
		return this.yuangongOne3;
	}

	public void setYuangongOne3(String yuangongOne3)
	{
		this.yuangongOne3 = yuangongOne3;
	}

	public String getYuangongOne4()
	{
		return this.yuangongOne4;
	}

	public void setYuangongOne4(String yuangongOne4)
	{
		this.yuangongOne4 = yuangongOne4;
	}

	public Date getYuangongOne5()
	{
		return this.yuangongOne5;
	}

	public void setYuangongOne5(Date yuangongOne5)
	{
		this.yuangongOne5 = yuangongOne5;
	}

	public Date getYuangongOne6()
	{
		return this.yuangongOne6;
	}

	public void setYuangongOne6(Date yuangongOne6)
	{
		this.yuangongOne6 = yuangongOne6;
	}

	public Integer getYuangongOne7()
	{
		return this.yuangongOne7;
	}

	public void setYuangongOne7(Integer yuangongOne7)
	{
		this.yuangongOne7 = yuangongOne7;
	}

	public Integer getYuangongOne8()
	{
		return this.yuangongOne8;
	}

	public void setYuangongOne8(Integer yuangongOne8)
	{
		this.yuangongOne8 = yuangongOne8;
	}

}//-------------------------请加下面QQ请求远程辅助运行代码  ID:1811--------------------------
//-----------------更多毕设, 联系QQ1305637939-------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加作者QQ协助运行: 1305637939-----------------------
//-------------------------请加下面QQ请求远程辅助运行代码----------------------------
